services:
  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - type: bind
          source: ./nginx-http.conf
          target: /etc/nginx/nginx.conf
        - type: bind
          source: ./
          target: /letsencrypt
        - type: bind
          source: ./certs
          target: /etc/letsencrypt